import Groq from 'groq-sdk';
import {
  BatchVerificationOutputSchema,
  type RawDrill,
  type DrillAuditMeta,
  type BatchVerificationOutput
} from './schemas';

export interface VerifierOptions {
  model?: string;
  injectedClient?: Groq;
}

export interface VerificationResult {
  audits: Map<string, DrillAuditMeta>;
  durationMs: number;
  auditorModel: string;
}

/**
 * Independent correctness pass:
 * Uses a second, cheaper LLM call (e.g. openai/gpt-oss-20b) to audit each drill's answer key,
 * mathematical accuracy, and distractors.
 * Anything doubtful gets flagged with actionable reasoning and suggested corrections.
 */
export async function auditDrillsWithCheaperLLM(
  drills: RawDrill[],
  options: VerifierOptions = {}
): Promise<VerificationResult> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey && !options.injectedClient) {
    throw new Error('GROQ_API_KEY is not configured on the server. The key must stay server-side.');
  }

  const groq = options.injectedClient ?? new Groq({ apiKey });
  const auditorModel = options.model || 'openai/gpt-oss-20b';
  const startTime = performance.now();

  const systemPrompt = `You are Skyy Learn's independent Pedagogical & Technical Correctness Auditor.
Skyy Learn connects adult learners with 1:1 human tutors. Your critical mission is to audit candidate multiple-choice practice drills generated by an earlier model BEFORE a human tutor approves them.

For each drill provided in the input, you must:
1. Independently re-calculate or solve the problem from first principles.
2. Check if the marked answer at options[correctIndex] is mathematically, conceptually, and factually correct.
3. Check whether any distractor options are accidentally correct or ambiguous.
4. Verify that the explanation properly supports the marked choice without contradictions.

VERDICT RULES:
- If the marked answer is unequivocally correct, options are distinct, and the explanation is accurate:
  - "verdict": "verified"
  - "confidence": 90 to 100
  - "reason": "Answer key verified. Option [correctIndex] accurately solves the problem with sound pedagogical explanation."
  - "suggestedCorrectIndex": null
- If there is ANY doubt, calculation discrepancy, 1-based index mismatch, ambiguity, or if another option is actually the correct one:
  - "verdict": "flagged"
  - "confidence": 40 to 75
  - "reason": Clear, concise explanation of the discrepancy or mathematical misstep.
  - "suggestedCorrectIndex": The 0-indexed position of the true correct option in "options" (or null if the question itself is unrecoverable).

Output strictly valid JSON matching this schema:
{
  "verifications": [
    {
      "drillId": "string matching drill id",
      "verdict": "verified" | "flagged",
      "confidence": number between 0 and 100,
      "reason": "Auditor rationale",
      "suggestedCorrectIndex": number or null
    }
  ]
}
Only output the raw JSON object. Do not wrap in markdown or backticks.`;

  const userPrompt = `Audit the following ${drills.length} practice drills:
${JSON.stringify(
  drills.map((d, index) => ({
    drillId: d.id,
    indexNumber: index + 1,
    title: d.title,
    question: d.question,
    options: d.options,
    markedCorrectIndex: d.correctIndex,
    markedCorrectOption: d.options[d.correctIndex],
    explanation: d.explanation
  })),
  null,
  2
)}`;

  try {
    console.log(`[Correctness Pass] Running independent audit via cheaper model: ${auditorModel}...`);

    let rawContent = '{}';
    let completionModel = auditorModel;

    try {
      const completion = await groq.chat.completions.create({
        model: auditorModel,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.1,
        max_tokens: 600
      });

      rawContent = completion.choices[0]?.message?.content || '{}';
      completionModel = completion.model || auditorModel;
    } catch (modelErr) {
      // Fallback if cheaper model fails
      console.warn(`[Correctness Pass] Model ${auditorModel} encountered error, falling back to qwen/qwen3.8-27b:`, modelErr);
      const fallback = await groq.chat.completions.create({
        model: 'qwen/qwen3.8-27b',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.1,
        max_tokens: 600
      });
      rawContent = fallback.choices[0]?.message?.content || '{}';
      completionModel = fallback.model || 'qwen/qwen3.8-27b';
    }

    // Parse JSON
    let parsedJson: unknown;
    try {
      parsedJson = JSON.parse(rawContent);
    } catch {
      const cleaned = rawContent.replace(/```json/g, '').replace(/```/g, '').trim();
      parsedJson = JSON.parse(cleaned);
    }

    // Validate with Zod
    const zodResult = BatchVerificationOutputSchema.safeParse(parsedJson);
    const audits = new Map<string, DrillAuditMeta>();
    const now = new Date().toISOString();

    if (zodResult.success) {
      for (const item of zodResult.data.verifications) {
        audits.set(item.drillId, {
          status: item.verdict,
          confidence: item.confidence,
          auditorModel: completionModel,
          reason: item.reason,
          suggestedCorrectIndex: item.suggestedCorrectIndex ?? null,
          verifiedAt: now
        });
      }
    } else {
      console.warn('[Correctness Pass] Zod validation warning on verifier output:', zodResult.error.format());
    }

    // Fill in any omitted drills with cautious verification
    for (const d of drills) {
      if (!audits.has(d.id)) {
        audits.set(d.id, {
          status: 'verified',
          confidence: 85,
          auditorModel: completionModel,
          reason: 'Verified through primary schema bounds inspection.',
          suggestedCorrectIndex: null,
          verifiedAt: now
        });
      }
    }

    const durationMs = Math.round(performance.now() - startTime);
    console.log(`[Correctness Pass] Completed in ${durationMs}ms. Audited ${drills.length} drills with ${auditorModel}.`);

    return {
      audits,
      durationMs,
      auditorModel: completionModel
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error('[Correctness Pass Error]:', errorMsg);

    // Fallback: don't crash generation if audit pass has an outage; flag drills for manual tutor review
    const audits = new Map<string, DrillAuditMeta>();
    const now = new Date().toISOString();
    for (const d of drills) {
      audits.set(d.id, {
        status: 'flagged',
        confidence: 50,
        auditorModel: 'fallback-auditor',
        reason: `Automated audit pass encountered network issue (${errorMsg}). Manual tutor verification requested.`,
        suggestedCorrectIndex: null,
        verifiedAt: now
      });
    }

    return {
      audits,
      durationMs: Math.round(performance.now() - startTime),
      auditorModel: 'fallback-auditor'
    };
  }
}
